// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xhavdgamnwxcpvaifieg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhoYXZkZ2Ftbnd4Y3B2YWlmaWVnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTczNDI2NjcsImV4cCI6MjA3MjkxODY2N30.-zweJlsK8MBtFUF8044TjMNpooyvDIZKdMSrdE4wgAQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});